# Generated by Django 4.1.2 on 2022-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('mobile_phone', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('role', models.CharField(max_length=4)),
                ('code', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
